### ISSUE TITLE
Can't see page content after building to local

### ISSUE THREAD

**Issue by venturewise** [Dnjoroge/editable-components#3]
I don't know if this is a true issue for this repo, or my own user issue, but after building this repo to local, the sample page is blank and this is the only error I see in the logs:
```

2020-10-11 01:02:21.332 ERROR [com.editable.components.core.listeners.EditableComponentsListener] Can neither derive user name nor principal names for bundle editable-components.core [599] and sub service editable-components-system-auth-user
javax.jcr.LoginException: Can neither derive user name nor principal names for bundle editable-components.core [599] and sub service editable-components-system-auth-user
```
Any idea how I can fix this? Thank you.

**Comment by Dnjoroge** [comment]
@venturewise This is fixed on this commit https://github.com/Dnjoroge/editable-components/commit/bbefb78494563d54afba585e7d35e74b5142f03e

Please install [ACS commons package](https://github.com/Adobe-Consulting-Services/acs-aem-commons/releases/download/acs-aem-commons-4.8.4/acs-aem-commons-content-4.8.4.zip) and redeploy

**Comment by helms-charity** [comment]
I redeployed your latest Master branch and the ACS commons. The good news is that I can't see any errors in the logs for en.html anymore. The bad news is that still the page is blank, and no page properties will show. 
- I also do not see any issues in the web console
- I was using AEM v. 6.5.3
- I am able to view and edit WKND and other sample content OK
- I am currently updateing to AEM 6.5.6 and will let you know if anything changes.
----------------------
Update: After upgrading to 6.5.6, I see content and page properties as expected! Thank you for your help.

**Comment by Dnjoroge** [comment]
I am glad everything worked as supposed to. I will go ahead and close this issue.
